#!/usr/bin/env node
/* ============================================================================
   audit-schema.mjs — Step 1 of the structured-data alignment.

   Extracts every <script type="application/ld+json"> block from the site's
   pages into schema/audit/<page>.json (pretty-printed, otherwise untouched)
   and writes schema/audit/inventory.md: types and @ids per page, diffs of
   shared @ids across pages, unresolved @id references, copy-rule hits,
   missing image files, and the geo coordinates on each page.

   Read-only with respect to the pages. Node 20+, no dependencies.
   ============================================================================ */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SITE = path.join(ROOT, 'public_html');
const OUT = path.join(ROOT, 'schema', 'audit');
const BASE = 'https://casaninaflamingo.com';
const PAGES = ['index', 'the-casa', 'gallery', 'book', 'faq', 'explore', 'concierge'];   // location.html was removed 2026-09-25

const CLICHES = ['paradise', 'oasis', 'nestled', 'breathtaking', 'stunning', 'ultimate', 'unforgettable', 'luxury'];
const NAMES = ['Karina', 'Rafael'];
mkdirSync(OUT, { recursive: true });

const md = [];
const log = (s = '') => md.push(s);

/* ---------- extract ---------- */
const pages = {};
for (const page of PAGES) {
  const html = readFileSync(path.join(SITE, page + '.html'), 'utf8');
  const blocks = [...html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)].map(m => m[1]);
  const parsed = blocks.map((b, i) => { try { return JSON.parse(b); } catch (e) { return { __parseError: `block ${i + 1}: ${e.message}` }; } });
  writeFileSync(path.join(OUT, page + '.json'), JSON.stringify(parsed.length === 1 ? parsed[0] : parsed, null, 2) + '\n');
  const geoMeta = /<meta name="geo.position" content="([^"]*)"/.exec(html)?.[1] || null;
  const icbm = /<meta name="ICBM" content="([^"]*)"/.exec(html)?.[1] || null;
  const canonical = /<link rel="canonical" href="([^"]*)"/.exec(html)?.[1] || null;
  pages[page] = { html, blocks: parsed, geoMeta, icbm, canonical };
}

/* ---------- walk nodes ---------- */
function nodesOf(doc) {
  const out = [];
  const walk = (o, parentId) => {
    if (!o || typeof o !== 'object') return;
    if (Array.isArray(o)) return o.forEach(x => walk(x, parentId));
    if (o['@type']) out.push(o);
    for (const [k, v] of Object.entries(o)) if (k !== '@context') walk(v, o['@id'] || parentId);
  };
  walk(doc); return out;
}
function refsOf(doc) {
  const refs = [];
  const walk = (o, keyPath) => {
    if (!o || typeof o !== 'object') return;
    if (Array.isArray(o)) return o.forEach((x, i) => walk(x, keyPath + '[' + i + ']'));
    const keys = Object.keys(o);
    if (keys.length === 1 && keys[0] === '@id') { refs.push({ id: o['@id'], at: keyPath }); return; }
    for (const [k, v] of Object.entries(o)) walk(v, keyPath ? keyPath + '.' + k : k);
  };
  walk(doc, ''); return refs;
}
function stringsOf(doc) {
  const out = [];
  const walk = (o, keyPath) => {
    if (typeof o === 'string') return out.push({ at: keyPath, s: o });
    if (!o || typeof o !== 'object') return;
    if (Array.isArray(o)) return o.forEach((x, i) => walk(x, keyPath + '[' + i + ']'));
    for (const [k, v] of Object.entries(o)) walk(v, keyPath ? keyPath + '.' + k : k);
  };
  walk(doc, ''); return out;
}
const typeStr = t => Array.isArray(t) ? t.join('+') : t;

/* ---------- per page: types & ids ---------- */
log('# Structured data inventory');
log('');
log(`Generated by scripts/audit-schema.mjs on ${new Date().toISOString().slice(0, 10)}. Raw blocks are in schema/audit/<page>.json.`);
log('');
log('Pages audited: ' + PAGES.map(p => p + '.html').join(', ') + '. (location.html was removed from the site before this audit.)');
log('');
log('## 1. Types and @ids per page');
log('');
const byId = {};   // id -> { page -> node }
for (const page of PAGES) {
  const P = pages[page];
  log(`### ${page}.html`);
  log(`- canonical: ${P.canonical || 'MISSING'}`);
  log(`- JSON-LD blocks: ${P.blocks.length}` + (P.blocks.some(b => b.__parseError) ? '  **PARSE ERROR: ' + P.blocks.filter(b => b.__parseError).map(b => b.__parseError).join('; ') + '**' : ''));
  const nodes = P.blocks.flatMap(nodesOf);
  const rows = nodes.map(n => `  - ${typeStr(n['@type'])}${n['@id'] ? '  ' + n['@id'] : ''}${n.name ? '  "' + String(n.name).slice(0, 60) + (String(n.name).length > 60 ? '…' : '') + '"' : ''}`);
  const seen = new Set(); rows.filter(r => !seen.has(r) && seen.add(r)).forEach(r => log(r));
  for (const n of nodes) if (n['@id']) { (byId[n['@id']] ||= {})[page] = n; }
  log('');
}

/* ---------- shared ids: property diffs ---------- */
log('## 2. @ids that appear on more than one page, property by property');
log('');
const canon = v => JSON.stringify(v);
let sharedCount = 0;
for (const [id, perPage] of Object.entries(byId)) {
  const ps = Object.keys(perPage); if (ps.length < 2) continue;
  sharedCount++;
  log(`### ${id}  (on ${ps.join(', ')})`);
  const props = new Set(); ps.forEach(p => Object.keys(perPage[p]).forEach(k => props.add(k)));
  let same = 0, diff = 0;
  for (const prop of [...props].sort()) {
    const vals = ps.map(p => canon(perPage[p][prop]));
    if (vals.every(v => v === vals[0])) { same++; continue; }
    diff++;
    log(`- **${prop}** differs:`);
    ps.forEach((p, i) => log(`  - ${p}: ${vals[i] === undefined ? '(absent)' : vals[i].length > 220 ? vals[i].slice(0, 220) + '…' : vals[i]}`));
  }
  log(`- ${same} propert${same === 1 ? 'y' : 'ies'} identical, ${diff} differ${diff === 1 ? 's' : ''}.`);
  log('');
}
if (!sharedCount) log('None.');

/* ---------- unresolved refs ---------- */
log('## 3. @id references that do not resolve on their own page');
log('');
let unresolved = 0;
for (const page of PAGES) {
  const ids = new Set(pages[page].blocks.flatMap(nodesOf).map(n => n['@id']).filter(Boolean));
  for (const r of pages[page].blocks.flatMap(refsOf)) if (!ids.has(r.id)) { unresolved++; log(`- ${page}.html: ${r.id}  (at ${r.at})`); }
}
if (!unresolved) log('None. Every {"@id"} reference resolves within its own page.');
log('');

/* ---------- copy rules ---------- */
log('## 4. Strings that trip a copy rule');
log('');
let hits = 0;
for (const page of PAGES) {
  for (const { at, s } of pages[page].blocks.flatMap(stringsOf)) {
    const problems = [];
    if (s.includes('—')) problems.push('em dash');
    if (/\[\[|TODO/.test(s)) problems.push('[[TOKEN]] or TODO');
    if (/\$\s?\d|\bUSD\b|\bprice/i.test(s)) problems.push('price');
    for (const n of NAMES) if (new RegExp('\\b' + n + '\\b').test(s)) problems.push('names ' + n);
    for (const c of CLICHES) if (new RegExp('\\b' + c + '\\b', 'i').test(s)) problems.push('cliché "' + c + '"' + (c === 'luxury' ? ' (check noun use)' : ''));
    if (problems.length) { hits++; log(`- ${page}.html  ${at}: ${problems.join(', ')}\n  > ${s.length > 160 ? s.slice(0, 160) + '…' : s}`); }
  }
}
if (!hits) log('None.');
log('');

/* ---------- images ---------- */
log('## 5. Image URLs whose file does not exist under public_html/');
log('');
let missing = 0; const checked = new Set();
for (const page of PAGES) {
  for (const { at, s } of pages[page].blocks.flatMap(stringsOf)) {
    if (!/\.(jpe?g|png|webp|gif|svg)(\?|$)/i.test(s)) continue;
    if (!s.startsWith(BASE + '/') && !/^images\//.test(s)) { if (/^https?:/.test(s)) continue; }
    const rel = s.replace(BASE + '/', '').split('?')[0];
    checked.add(rel);
    if (!existsSync(path.join(SITE, rel))) { missing++; log(`- ${page}.html  ${at}: ${s}`); }
  }
}
log(missing ? '' : `None. ${checked.size} distinct image files referenced, all present.`);
log('');

/* ---------- geo ---------- */
log('## 6. Geo coordinates per page');
log('');
log('| page | geo.position meta | ICBM meta | JSON-LD GeoCoordinates | hasMap |');
log('|---|---|---|---|---|');
for (const page of PAGES) {
  const nodes = pages[page].blocks.flatMap(nodesOf);
  const geos = nodes.filter(n => typeStr(n['@type']) === 'GeoCoordinates').map(n => `${n.latitude}, ${n.longitude}`);
  const maps = [...new Set(pages[page].blocks.flatMap(stringsOf).filter(x => /hasMap/.test(x.at)).map(x => x.s))];
  log(`| ${page} | ${pages[page].geoMeta || '(none)'} | ${pages[page].icbm || '(none)'} | ${geos.length ? [...new Set(geos)].join('; ') : '(none)'} | ${maps.length ? maps.join('; ') : '(none)'} |`);
}
log('');

writeFileSync(path.join(OUT, 'inventory.md'), md.join('\n') + '\n');
console.log(md.join('\n'));
